# Generated by Django 5.1.6 on 2025-02-28 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid mobile number format. Valid formats: (911)667-3914, 911-667-3914, +1-911-667-3914, etc.', regex='^(\\+?\\d{1,3}[-.\\s]?)?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$')]),
        ),
    ]
